apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernoorain-eta-deploy
  labels:
    app: kubernoorain-eta-deploy-lbl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubenoorain-eta-app
  template:
    metadata:
      labels:
        app: kubenoorain-eta-app
    spec:
      containers:
      - name: kubenoorain-eta-container
        image: kubenoorain/my-java-app:latest
        volumeMounts:
      - mountPath: /test-mnt
        name: test-vol
        ports:
        - containerPort: 8080
      volumes:
      - name: test-vol
        hostPath:
          path: /test-vol
---
apiVersion: v1
kind: Service
metadata:
  name: kubernoorain-eta-np-service
  labels:
    app: kubernoorain-eta-np-app
spec:
  selector:
    app: kubernoorain-eta-deploy-lbl

  type: NodePort
  ports:
  - nodePort: 31028
    port: 8080
    targetPort: 8080
